### ISSUE TITLE
error while observer running PY:SETUP

### ISSUE THREAD

**Issue by muyang** [qiemem/PythonExtension#14]
Dear bro,
Thanks a lot for your awesome python extension.
I try to build the extension and run the demo, but met some errors.

OS: Ubuntu 16.04 LTS
NetLogo: 6.0.3
python: all Standard Library can be used without problems

Could you offer any help  and suggestion?

`error info`

**Problem 1 : sbt build successfully, but end with some errors.**
```
[info] Loading project definition from /home/mu/PythonExtension/project
[info] Set current project to pythonextension (in build file:/home/mu/PythonExtension/)
[info] Updating {file:/home/mu/PythonExtension/}pythonextension...
[info] Resolving jline#jline;2.14.3 ...
[info] downloading https://dl.bintray.com/content/netlogo/NetLogo-JVM/org/nlogo/netlogo/6.0.3/netlogo-6.0.3-tests.jar ...
[info] 	[SUCCESSFUL ] org.nlogo#netlogo;6.0.3!netlogo.jar (3123ms)
[info] downloading https://dl.bintray.com/content/netlogo/NetLogo-JVM/org/nlogo/netlogo/6.0.3/netlogo-6.0.3.jar ...
[info] 	[SUCCESSFUL ] org.nlogo#netlogo;6.0.3!netlogo.jar (8924ms)
[info] Done updating.
[warn] Found intransitive dependency (org.nlogo:netlogo:6.0.3) while publishMavenStyle is true, but Maven repositories
[warn]   do not support intransitive dependencies. Use exclusions instead so transitive dependencies
[warn]   will be correctly excluded in dependent projects.
[warn]            
[info] Compiling 2 Scala sources to /home/mu/PythonExtension/target/scala-2.12/classes...
[info] Packaging /home/mu/PythonExtension/target/scala-2.12/py.jar ...
[info] Done packaging.
[success] Total time: 33 s, completed Apr 24, 2018 10:32:45 PM
[error] Expected letter
[error] Expected symbol
[error] Expected '!'
[error] Expected '+'
[error] Expected '++'
[error] Expected '^'
[error] Expected '^^'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected ';'
[error] Expected end of input.
[error] Expected 'early('
[error] Expected '-'
[error] Expected '--'
[error] Expected 'show'
[error] Expected 'all'
[error] Expected '*'
[error] Expected '{'
[error] Expected project ID
[error] Expected configuration
[error] Expected key
[error] .
[error] ^
```

**Problem2: error while observer running PY:SETUP**
```
Extension exception: Failed to find execution shell. This is a bug. Please report.
error while observer running PY:SETUP
  called by procedure SETUP
  called by Button 'setup'

org.nlogo.nvm.WrappedExtensionException: Extension exception: Failed to find execution shell. This is a bug. Please report.
 at org.nlogo.prim._extern.perform(_extern.java:40)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: Failed to find execution shell. This is a bug. Please report.
 at org.nlogo.py.PythonSubprocess$.start(PythonExtension.scala:186)
 at org.nlogo.py.SetupPython$.perform(PythonExtension.scala:542)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 ... 8 more
Caused by: java.io.IOException: Cannot run program "/home/mu/NetLogo-6.0.3/app/~/tensorflow/bin/python2.7" (in directory "/home/mu/NetLogo-6.0.3/app/extensions/py/demos"): error=2, No such file or directory
 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
 at org.nlogo.py.PythonSubprocess$.start(PythonExtension.scala:183)
 ... 10 more
Caused by: java.io.IOException: error=2, No such file or directory
 at java.lang.UNIXProcess.forkAndExec(Native Method)
 at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
 at java.lang.ProcessImpl.start(ProcessImpl.java:134)
 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
 ... 11 more

NetLogo 6.0.3
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_162 (Oracle Corporation; 1.8.0_162-b12)
operating system: Linux 4.13.0-37-generic (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Flocking Clusters

10:39:16.414 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
10:39:16.387 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
10:39:16.384 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:39:16.384 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread

```

**Comment by muyang** [comment]
Dear Bro,
I hv already found the problem. Because the python path I configured was in virtualenv. when I do not use that path, no error anymore.
But, in terminal, the path is available. 
Seeing

```
$ ~/tensorflow/bin/python2.7
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn.cluster as cl
>>> import numpy as np
>>> 
```
'cause I have installed tensorflow and keras in virtualenv, any possible way that I can use path of virtualenv python in configure ?

Thank you for your time.

**Comment by qiemem** [comment]
Thanks for trying out the Python extension! `py:setup` just takes a path to the python binary, so you should be able to just run `py:setup "~/tensorflow/bin/python2.7"`. Does that work?

**Comment by muyang** [comment]
thank you for your instant answer. 
still the same error.
It may be the problem that could not find the python path in virtualenv.

**Comment by qiemem** [comment]
Hmm, okay, can you try writing the full path like so `py:setup "/home/mu/tensorflow/bin/python2.7"`?

**Comment by muyang** [comment]
okey, it is midnignt here:grinning:. I am on the bus back to my flat now. I will try when I arrive home.

**Comment by qiemem** [comment]
Sorry for keeping you up! Thanks for diagnosing with me. I think all that's happening here is that `py:setup` doesn't expand normal bash stuff like `~` (it doesn't use bash on linux; it executes the command directly). The error message definitely needs to be better at the very least, though.

**Comment by muyang** [comment]
Bro, never mind, I usually sleep late.
I just try the full path, it works now!
Very cool demos! Now I can use python's libraries, connecting two worlds python and Logo.
Again many thanks for your time and support!

**Comment by qiemem** [comment]
Great to hear! Let me know if you run into any more trouble!
